<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TaxObjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tax_objects')->insert([
            [
                'id_object' => 3,
                'tax_cluster_id' => 1,
                'kode_objek' => '24-104-01',
                'nama_objek' => 'Jasa & Sewa Harta',
                'deskripsi' => 'Jasa Manajemen, Jasa Konsultasi, Jasa Teknik & Jasa Lainnya',
                'dasar_hukum' => 'PMK-141/PMK.03/2015 & PER-24/PJ/2021',
                'tarif' => 2.00,
                'status' => 'aktif',
            ],
            [
                'id_object' => 4,
                'tax_cluster_id' => 1,
                'kode_objek' => '24-104-02',
                'nama_objek' => 'Jasa & Sewa Harta',
                'deskripsi' => 'Jasa Perawatan / Pemeliharaan / Perbaikan Mesin & Bangunan',
                'dasar_hukum' => 'PMK-141/PMK.03/2015',
                'tarif' => 2.00,
                'status' => 'aktif',
            ],
            [
                'id_object' => 5,
                'tax_cluster_id' => 1,
                'kode_objek' => '24-104-03',
                'nama_objek' => 'Jasa & Sewa Harta',
                'deskripsi' => 'Jasa Kebersihan (Cleaning Service) & Keamanan (Security)',
                'dasar_hukum' => 'PMK-141/PMK.03/2015',
                'tarif' => 2.00,
                'status' => 'aktif',
            ],
            [
                'id_object' => 6,
                'tax_cluster_id' => 1,
                'kode_objek' => '24-104-04',
                'nama_objek' => 'Jasa & Sewa Harta',
                'deskripsi' => 'Jasa IT, Software Development, Server & Maintenance Web',
                'dasar_hukum' => 'PMK-141/PMK.03/2015',
                'tarif' => 2.00,
                'status' => 'aktif',
            ],
            [
                'id_object' => 7,
                'tax_cluster_id' => 1,
                'kode_objek' => '24-104-05',
                'nama_objek' => 'Jasa & Sewa Harta',
                'deskripsi' => 'Jas Freight Forwarding, Logistik & Ekspedisi Pengiriman',
                'dasar_hukum' => 'PMK-141/PMK.03/2015',
                'tarif' => 2.00,
                'status' => 'aktif',
            ],
            [
                'id_object' => 8,
                'tax_cluster_id' => 1,
                'kode_objek' => '24-102-01',
                'nama_objek' => 'Jasa & Sewa Harta',
                'deskripsi' => 'Sewa & Penggunaan Harta (Selain Tanah dan/atau Bangunan)',
                'dasar_hukum' => 'Pasal 23 ayat (1) huruf c UU PPh',
                'tarif' => 2.00,
                'status' => 'aktif',
            ],
            [
                'id_object' => 9,
                'tax_cluster_id' => 1,
                'kode_objek' => '24-100-01',
                'nama_objek' => 'Jasa & Sewa Harta',
                'deskripsi' => 'Dividen Diterima Wajib Pajak Badan Dalam Negeri',
                'dasar_hukum' => 'Pasal 23 ayat (1) huruf a UU PPh',
                'tarif' => 15.00,
                'status' => 'aktif',
            ],
            [
                'id_object' => 10,
                'tax_cluster_id' => 1,
                'kode_objek' => '24-101-01',
                'nama_objek' => 'Jasa & Sewa Harta',
                'deskripsi' => 'Bunga Pinjaman (Selain Bunga Bank)',
                'dasar_hukum' => 'Pasal 23 ayat (1) huruf a UU PPh',
                'tarif' => 15.00,
                'status' => 'aktif',
            ],
            [
                'id_object' => 11,
                'tax_cluster_id' => 1,
                'kode_objek' => '24-103-01',
                'nama_objek' => 'Jasa & Sewa Harta',
                'deskripsi' => 'Royalti Atas Penggunaan Hak Cipta, Paten, Merk Dagang',
                'dasar_hukum' => 'Pasal 23 ayat (1) huruf a UU PPh',
                'tarif' => 15.00,
                'status' => 'aktif',
            ],
            [
                'id_object' => 12,
                'tax_cluster_id' => 1,
                'kode_objek' => '24-105-01',
                'nama_objek' => 'Jasa & Sewa Harta',
                'deskripsi' => 'Hadiah, Penghargaan & Bonus Selain PPh 21',
                'dasar_hukum' => 'Pasal 23 ayat (1) huruf a UU PPh',
                'tarif' => 15.00,
                'status' => 'aktif',
            ],

            // PPh Pasal 4 ayat (2)
            [
                'id_object' => 13,
                'tax_cluster_id' => 2,
                'kode_objek' => '28-402-01',
                'nama_objek' => 'Sewa Gedung & Kontruksi',
                'deskripsi' => 'Sewa Tanah dan/atau Bangunan (Gedung, Kantor, Ruko, Gudang)',
                'dasar_hukum' => 'PP No. 34 Tahun 2017',
                'tarif' => 10.00,
                'status' => 'aktif',
            ],
            [
                'id_object' => 14,
                'tax_cluster_id' => 2,
                'kode_objek' => '28-403-01',
                'nama_objek' => 'Sewa Gedung & Kontruksi',
                'deskripsi' => 'Pengalihan Hak atas Tanah dan/atau Bangunan',
                'dasar_hukum' => 'PP No. 34 Tahun 2016',
                'tarif' => 2.50,
                'status' => 'aktif',
            ],
            [
                'id_object' => 15,
                'tax_cluster_id' => 2,
                'kode_objek' => '28-409-01',
                'nama_objek' => 'Sewa Gedung & Kontruksi',
                'deskripsi' => 'Jasa Kontruksi - Pelaksanaan (Sertifikat Kualifikasi Kecil)',
                'dasar_hukum' => 'PP No. 9 Tahun 2022',
                'tarif' => 1.75,
                'status' => 'aktif',
            ],
            [
                'id_object' => 16,
                'tax_cluster_id' => 2,
                'kode_objek' => '28-409-02',
                'nama_objek' => 'Sewa Gedung & Kontruksi',
                'deskripsi' => 'Jasa Konstruksi - Pelaksanaan (Kualifikasi Menengah / Besar)',
                'dasar_hukum' => 'PP No. 9 Tahun 2022',
                'tarif' => 2.65,
                'status' => 'aktif',
            ],
            [
                'id_object' => 17,
                'tax_cluster_id' => 2,
                'kode_objek' => '28-409-03',
                'nama_objek' => 'Sewa Gedung & Kontruksi',
                'deskripsi' => 'Jasa Konstruksi - Konsultasi / Pengawasan Bersertifikat',
                'dasar_hukum' => 'PP No. 9 Tahun 2022',
                'tarif' => 3.50,
                'status' => 'aktif',
            ],
            [
                'id_object' => 18,
                'tax_cluster_id' => 2,
                'kode_objek' => '28-409-04',
                'nama_objek' => 'Sewa Gedung & Kontruksi',
                'deskripsi' => 'Jasa Konstruksi - Pelaksanaan Tanpa Sertifikat Kualikasi',
                'dasar_hukum' => 'PP No. 9 Tahun 2022',
                'tarif' => 4.00,
                'status' => 'aktif',
            ],
            [
                'id_object' => 19,
                'tax_cluster_id' => 2,
                'kode_objek' => '28-401-01',
                'nama_objek' => 'Sewa Gedung & Kontruksi',
                'deskripsi' => 'Bunga Deposito, Tabungan & Diskonto SBI',
                'dasar_hukum' => 'PP No. 131 Tahun 2000',
                'tarif' => 20.00,
                'status' => 'aktif',
            ],
            [
                'id_object' => 20,
                'tax_cluster_id' => 2,
                'kode_objek' => '28-419-01',
                'nama_objek' => 'Sewa Gedung & Kontruksi',
                'deskripsi' => 'Dividen Diterima Wajib Pajak Orang Pribadi Dalam Negeri',
                'dasar_hukum' => 'Pasal 17 ayat (2c) UU PPh & UU HPP',
                'tarif' => 10.00,
                'status' => 'aktif',
            ],

            // PPh Pasal 22
            [
                'id_object' => 21,
                'tax_cluster_id' => 3,
                'kode_objek' => '22-100-01',
                'nama_objek' => 'Pengadaan Barang',
                'deskripsi' => 'Pengadaan / Pembeliaan Barang oleh Instansi Pemerintah & BUMN',
                'dasar_hukum' => 'PMK-59/PMK.03/2022 & PMK-34/2017',
                'tarif' => 1.50,
                'status' => 'aktif',
            ],
            [
                'id_object' => 22,
                'tax_cluster_id' => 3,
                'kode_objek' => '22-100-02',
                'nama_objek' => 'Pengadaan Barang',
                'deskripsi' => 'Penjualan Bahan Bakar Minyak & Pelumas oleh Pertamina/Produsen',
                'dasar_hukum' => 'PMK-34/PMK.010/2017',
                'tarif' => 0.25,
                'status' => 'aktif',
            ],
            [
                'id_object' => 23,
                'tax_cluster_id' => 3,
                'kode_objek' => '22-101-01',
                'nama_objek' => 'Pengadaan Barang',
                'deskripsi' => 'Impor Barang Menggunakan API (Angka Pengenal Impor)',
                'dasar_hukum' => 'PMK-34/PMK.010/2017',
                'tarif' => 2.50,
                'status' => 'aktif',
            ],

            // PPh Pasal 15
            [
                'id_object' => 24,
                'tax_cluster_id' => 4,
                'kode_objek' => '25-100-01',
                'nama_objek' => 'Pelayaran & Penerbangan',
                'deskripsi' => 'Imbalan Jasa Pelayaran Dalam Negeri (Charter Kapal/Freight)',
                'dasar_hukum' => 'KMK No. 416/KMK.04/1996',
                'tarif' => 1.20,
                'status' => 'aktif',
            ],
            [
                'id_object' => 25,
                'tax_cluster_id' => 4,
                'kode_objek' => '25-100-02',
                'nama_objek' => 'Pelayaran & Penerbangan',
                'deskripsi' => 'Imbalan Jasa Penerbangan Dalam Negeri (Charter Pesawat)',
                'dasar_hukum' => 'KMK No. 475/KMK.04/1996',
                'tarif' => 0.00,
                'status' => 'aktif',
            ],

            // PPh Pasal 26
            [
                'id_object' => 26,
                'tax_cluster_id' => 5,
                'kode_objek' => '27-100-01',
                'nama_objek' => 'Vendor Luar Negeri',
                'deskripsi' => 'Imbalan Jasa Teknik, Manajemen, IT & Jasa Lainnya ke WPLN',
                'dasar_hukum' => 'Pasal 26 ayat (1) UU PPh / Tax Treaty',
                'tarif' => 20.00,
                'status' => 'aktif',
            ],
            [
                'id_object' => 27,
                'tax_cluster_id' => 5,
                'kode_objek' => '27-100-03',
                'nama_objek' => 'Vendor Luar Negeri',
                'deskripsi' => 'Royalti, Lisensi & Hak Penggunaan Cipta ke WPLN',
                'dasar_hukum' => 'Pasal 26 ayat (1) UU PPh / Tax Treaty',
                'tarif' => 20.00,
                'status' => 'aktif',
            ],
        ]);
    }
}
